OOP school library: preserve data
Uzair-Manzoor/school-library-app pull request #7
Opened 2023-11-22 17:01 UTC by Uzair-Manzoor

## This pull request has been created against the below mentioned new implementations into the project:

- [x] Created serialize_to_json and deserialize_from_json methods to handle JSON serialization.
- [x] Created PersonFactory module to handle person-related operations.
- [x] Created BookFactory and RentalFactory modules to handle book and rental operations.

2023-11-22 17:42 UTC, Abenezer-Tilahun requested changes
Hi @Uzair-Manzoor @enocol 

Great job for implemented  the some of the Project Requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linter errors
✔️ Correct Git-Flow
✔️ Good commit messages
✔️ Correctly  save all the data of books in JSON files on the exit of the app and On startup of your app load all data from files.

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/70da70b4-a280-49d5-9c25-595f1794f686)
![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/6486f5c4-e66a-4130-b927-dc7e58191ddd)

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [x] Kindly make sure that "List all peoples " and "Create a rental" method are working as expected when I checked both of the method it throws  an error as shown below with the below screenshot Kindly fix the issues.
![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/47c26d7d-78d6-4f70-8e37-bbc3b5ca4ef1)
![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/0a31ebcf-3fa7-4fd9-9210-0b0541fd1e70)




_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-22 17:42 UTC, Abenezer-Tilahun commented on person_factory.rb
> +end
- [x] As stated in the project requirement **On exit from your app save all the data people,  into JSON files.** but when I checked the people data are saved or not in` json` file on the exit of app , your app throw an error as shown with the below screenshot Kindly Fix the issues.
![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/8ed3bf69-c141-4f54-b5bc-6a0b6ac1bc79)

2023-11-22 17:42 UTC, Abenezer-Tilahun commented on rental_factory.rb
> +end
- [x] As stated in the project requirement **On exit from your app save all the data rentals,  into JSON files.** but when I checked the rentals data are saved or not in` json` file on the exit of app and try to create a rental  , your app throw an error as shown with the below screenshot Kindly Fix the issues.
![image](https://github.com/Uzair-Manzoor/school-library-app/assets/93598189/23cd86aa-f272-4a50-858b-f9654ae0c70b)

2023-11-22 19:02 UTC, aamirkhan2478 requested changes
Hi @Uzair-Manzoor & @enocol, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-22 19:02 UTC, aamirkhan2478 commented on person_factory.rb
> +    end
- [ ] As mentioned by the previous :point_up: reviewer as stated in the project requirement `On exit from your app saves all the data people`, into `JSON` files. but when I checked the people data are saved or not in `json` file on the exit of the app so kindly fix this issue :slightly_smiling_face:

2023-11-22 19:02 UTC, aamirkhan2478 commented on rental_factory.rb
> +    end
- [ ] As mentioned by the previous :point_up: reviewer as stated in the project requirement `On exit from your app save all the data rentals`, into `JSON` files. but when I checked the rental data were saved or not in `json` file on the exit of app so kindly fix this issue as well :slightly_smiling_face:

2023-11-23 03:58 UTC, Uzair-Manzoor commented
Hi @aamirkhan2478, the app is working perfectly with all functionalities after recent amendments. Screenshots are attached for clear understanding

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/99558868/df4e765c-5d14-4019-81f9-f5b18ca9bb68)

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/99558868/2b23a6dd-fe50-4484-8ed6-c69d37690a9e)

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/99558868/dd67933e-1bcf-4f44-b4a1-77b6be9d351d)

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/99558868/614f3caf-eec4-439f-be21-3c14caae8de6)

![image](https://github.com/Uzair-Manzoor/school-library-app/assets/99558868/36ce355e-6a21-465c-84b8-e3eadb99e2a2)

2023-11-23 04:12 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Everything works perfectly and the data is saved in JSON files. ✔
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-23 04:48 UTC, merged